version: '3.4'

services:
  vega.api:
    image: ${DOCKER_REGISTRY-}vegaapi
    build:
      context: .
      dockerfile: Vega.Api/Dockerfile
    ports:
        - "8000:80"
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "MyPassword123!"
        ACCEPT_EULA: "Y"